name: sf_cli
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  args: ^2.3.0
  process_run: ^0.12.2
  test:

dev_dependencies:
  lints: ^3.0.0
